
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.0.0
//   File : Durandal.API.RecoResult_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.0.0")]
    public partial class RecoResult
    {
        [global::Bond.Id(1), global::Bond.Required]
        public string Domain { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public string Intent { get; set; }

        [global::Bond.Id(3), global::Bond.Required]
        public float Confidence { get; set; }

        [global::Bond.Id(4)]
        public Sentence Utterance { get; set; }

        [global::Bond.Id(5)]
        public List<TaggedData> TagHyps { get; set; }

        [global::Bond.Id(6)]
        public string Source { get; set; }

        public RecoResult()
            : this("Durandal.API.RecoResult", "RecoResult")
        {}

        protected RecoResult(string fullName, string name)
        {
            Domain = "";
            Intent = "";
            Confidence = 0.0F;
            Utterance = new Sentence();
            TagHyps = new List<TaggedData>();
            Source = "";
        }
    }
} // Durandal.API
