
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.0.0
//   File : Durandal.API.ClientContext_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.0.0")]
    public partial class ClientContext
    {
        [global::Bond.Id(1), global::Bond.Required]
        public string ClientId { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public uint Capabilities { get; set; }

        [global::Bond.Id(3), global::Bond.Required]
        public string Locale { get; set; }

        [global::Bond.Id(4), global::Bond.Required]
        public string UserId { get; set; }

        [global::Bond.Id(5)]
        public string ClientName { get; set; }

        [global::Bond.Id(6)]
        public string ReferenceDateTime { get; set; }

        [global::Bond.Id(7), global::Bond.Type(typeof(global::Bond.Tag.nullable<int>))]
        public int? UTCOffset { get; set; }

        [global::Bond.Id(8), global::Bond.Type(typeof(global::Bond.Tag.nullable<double>))]
        public double? Latitude { get; set; }

        [global::Bond.Id(9), global::Bond.Type(typeof(global::Bond.Tag.nullable<double>))]
        public double? Longitude { get; set; }

        [global::Bond.Id(10), global::Bond.Type(typeof(global::Bond.Tag.nullable<double>))]
        public double? LocationAccuracy { get; set; }

        [global::Bond.Id(11)]
        public Dictionary<string, string> Data { get; set; }

        [global::Bond.Id(12)]
        public HashSet<string> SupportedClientActions { get; set; }

        public ClientContext()
            : this("Durandal.API.ClientContext", "ClientContext")
        {}

        protected ClientContext(string fullName, string name)
        {
            ClientId = "";
            Capabilities = 0;
            Locale = "";
            UserId = "0";
            ClientName = "";
            ReferenceDateTime = "";
            Data = new Dictionary<string, string>();
            SupportedClientActions = new HashSet<string>();
        }
    }
} // Durandal.API
