
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.0.0
//   File : Durandal.API.SecurityToken_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.0.0")]
    public partial class SecurityToken
    {
        [global::Bond.Id(1), global::Bond.Required]
        public string Red { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public string Blue { get; set; }

        [global::Bond.Id(3)]
        public ClientAuthenticationScope Scope { get; set; }

        public SecurityToken()
            : this("Durandal.API.SecurityToken", "SecurityToken")
        {}

        protected SecurityToken(string fullName, string name)
        {
            Red = "";
            Blue = "";
            Scope = ClientAuthenticationScope.None;
        }
    }
} // Durandal.API
