
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.0.0
//   File : Durandal.API.ClientRequest_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.0.0")]
    public partial class ClientRequest
    {
        [global::Bond.Id(1), global::Bond.Required]
        public int ProtocolVersion { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public ClientContext ClientContext { get; set; }

        [global::Bond.Id(3), global::Bond.Required]
        public InputMethod InputType { get; set; }

        [global::Bond.Id(4)]
        public List<SpeechHypothesis> Queries { get; set; }

        [global::Bond.Id(5), global::Bond.Type(typeof(global::Bond.Tag.nullable<SecurityToken>))]
        public SecurityToken AuthToken { get; set; }

        [global::Bond.Id(6), global::Bond.Type(typeof(global::Bond.Tag.nullable<AudioData>))]
        public AudioData QueryAudio { get; set; }

        [global::Bond.Id(7), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<RecoResult>>))]
        public List<RecoResult> UnderstandingData { get; set; }

        [global::Bond.Id(8), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string PreferredAudioCodec { get; set; }

        [global::Bond.Id(9), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string TraceId { get; set; }

        [global::Bond.Id(10), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<string>>))]
        public List<string> DomainScope { get; set; }

        [global::Bond.Id(11), global::Bond.Type(typeof(global::Bond.Tag.nullable<int>))]
        public int? ClientAudioPlaybackTimeMs { get; set; }

        [global::Bond.Id(12)]
        public uint RequestFlags { get; set; }

        public ClientRequest()
            : this("Durandal.API.ClientRequest", "ClientRequest")
        {}

        protected ClientRequest(string fullName, string name)
        {
            ProtocolVersion = 14;
            ClientContext = new ClientContext();
            InputType = InputMethod.Unknown;
            Queries = new List<SpeechHypothesis>();
            RequestFlags = 0;
        }
    }
} // Durandal.API
