
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.0.0
//   File : Durandal.API.ClientResponse_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.0.0")]
    public partial class ClientResponse
    {
        [global::Bond.Id(1), global::Bond.Required]
        public int ProtocolVersion { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public Result ExecutionResult { get; set; }

        [global::Bond.Id(3), global::Bond.Required]
        public bool ContinueImmediately { get; set; }

        [global::Bond.Id(4)]
        public string ResponseText { get; set; }

        [global::Bond.Id(5)]
        public string ResponseUrl { get; set; }

        [global::Bond.Id(6)]
        public string ResponseHtml { get; set; }

        [global::Bond.Id(7), global::Bond.Type(typeof(global::Bond.Tag.nullable<int>))]
        public int? SuggestedRetryDelay { get; set; }

        [global::Bond.Id(8)]
        public string ErrorMessage { get; set; }

        [global::Bond.Id(9)]
        public Dictionary<string, string> ResponseData { get; set; }

        [global::Bond.Id(10)]
        public string AugmentedFinalQuery { get; set; }

        [global::Bond.Id(11), global::Bond.Type(typeof(global::Bond.Tag.nullable<AudioData>))]
        public AudioData ResponseAudio { get; set; }

        [global::Bond.Id(12)]
        public string ResponseSsml { get; set; }

        [global::Bond.Id(13), global::Bond.Type(typeof(global::Bond.Tag.nullable<RecoResult>))]
        public RecoResult SelectedRecoResult { get; set; }

        [global::Bond.Id(14)]
        public UrlScope UrlScope { get; set; }

        [global::Bond.Id(15)]
        public string StreamingAudioUrl { get; set; }

        [global::Bond.Id(16)]
        public AudioOrdering CustomAudioOrdering { get; set; }

        [global::Bond.Id(17)]
        public bool IsRetrying { get; set; }

        [global::Bond.Id(18)]
        public string ResponseAction { get; set; }

        [global::Bond.Id(19)]
        public List<string> SuggestedQueries { get; set; }

        [global::Bond.Id(20)]
        public List<TriggerKeyword> TriggerKeywords { get; set; }

        [global::Bond.Id(21), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<InstrumentationEvent>>))]
        public List<InstrumentationEvent> TraceInfo { get; set; }

        [global::Bond.Id(22), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string TraceId { get; set; }

        [global::Bond.Id(23), global::Bond.Type(typeof(global::Bond.Tag.nullable<int>))]
        public int? ConversationLifetimeSeconds { get; set; }

        public ClientResponse()
            : this("Durandal.API.ClientResponse", "ClientResponse")
        {}

        protected ClientResponse(string fullName, string name)
        {
            ProtocolVersion = 14;
            ExecutionResult = Result.Failure;
            ContinueImmediately = false;
            ResponseText = "";
            ResponseUrl = "";
            ResponseHtml = "";
            ErrorMessage = "";
            ResponseData = new Dictionary<string, string>();
            AugmentedFinalQuery = "";
            ResponseSsml = "";
            UrlScope = UrlScope.Unknown;
            StreamingAudioUrl = "";
            CustomAudioOrdering = AudioOrdering.AfterSpeech;
            IsRetrying = false;
            ResponseAction = "";
            SuggestedQueries = new List<string>();
            TriggerKeywords = new List<TriggerKeyword>();
        }
    }
} // Durandal.API
