
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.0.0
//   File : Durandal.API.LURequest_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.0.0")]
    public partial class LURequest
    {
        [global::Bond.Id(1), global::Bond.Required]
        public int ProtocolVersion { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public List<SpeechHypothesis> Utterances { get; set; }

        [global::Bond.Id(3), global::Bond.Required]
        public ClientContext Context { get; set; }

        [global::Bond.Id(4)]
        public bool DoFullAnnotation { get; set; }

        [global::Bond.Id(5)]
        public bool IsSpeechQuery { get; set; }

        [global::Bond.Id(6)]
        public string TraceId { get; set; }

        [global::Bond.Id(7)]
        public List<string> DomainScope { get; set; }

        [global::Bond.Id(8)]
        public uint RequestFlags { get; set; }

        public LURequest()
            : this("Durandal.API.LURequest", "LURequest")
        {}

        protected LURequest(string fullName, string name)
        {
            ProtocolVersion = 14;
            Utterances = new List<SpeechHypothesis>();
            Context = new ClientContext();
            DoFullAnnotation = true;
            IsSpeechQuery = false;
            TraceId = "";
            DomainScope = new List<string>();
            RequestFlags = 0;
        }
    }
} // Durandal.API
