
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.0.0
//   File : Durandal.API.Sentence_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.10.0.0")]
    public partial class Sentence
    {
        [global::Bond.Id(1), global::Bond.Required]
        public string OriginalText { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public List<string> Words { get; set; }

        [global::Bond.Id(3), global::Bond.Required]
        public List<int> Indices { get; set; }

        [global::Bond.Id(4)]
        public string LexicalForm { get; set; }

        [global::Bond.Id(5)]
        public List<string> NonTokens { get; set; }

        public Sentence()
            : this("Durandal.API.Sentence", "Sentence")
        {}

        protected Sentence(string fullName, string name)
        {
            OriginalText = "";
            Words = new List<string>();
            Indices = new List<int>();
            LexicalForm = "";
            NonTokens = new List<string>();
        }
    }
} // Durandal.API
