
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.0.0
//   File : Durandal.API.ClientAuthenticationLevel_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.API
{
    using System;
    using System.Collections.Generic;

    [Flags]
    public enum ClientAuthenticationLevel
    {
        None = 0x0,
        ClientUnknown = 0x1 << 1,
        ClientUnverified = 0x1 << 2,
        ClientAuthorized = 0x1 << 3,
        ClientUnauthorized = 0x1 << 4,
        UserUnknown = 0x1 << 5,
        UserUnverified = 0x1 << 6,
        UserAuthorized = 0x1 << 7,
        UserUnauthorized = 0x1 << 8,
    }
} // Durandal.API
