
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.0.0
//   File : Durandal.API.PluginInformation_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.API
{
    using Durandal.Common.Utils;
    using Durandal.Common.IO.Json;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class LocalizedInformation
    {
        public string DisplayName { get; set; }

        public string Creator { get; set; }

        public string ShortDescription { get; set; }

        public List<string> SampleQueries { get; set; }
        
        public LocalizedInformation()
        {
            DisplayName = "";
            Creator = "";
            ShortDescription = "";
            SampleQueries = new List<string>();
        }
    }

    public class PluginInformation
    {
        public string InternalName { get; set; }

        public ushort MajorVersion { get; set; }

        public ushort MinorVersion { get; set; }

        public string Creator { get; set; }

        public Dictionary<string, LocalizedInformation> LocalizedInfo { get; set; }

        [JsonConverter(typeof(JsonByteArrayConverter))]
        public System.ArraySegment<byte> IconPngData { get; set; }

        public bool Hidden { get; set; }

        public bool Configurable { get; set; }
        
        public PluginInformation()
        {
            InternalName = "";
            Creator = "";
            LocalizedInfo = new Dictionary<string, LocalizedInformation>();
            IconPngData = new System.ArraySegment<byte>();
            Hidden = false;
            Configurable = false;
        }
    }
} // Durandal.API
