
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.1.0
//   File : Durandal.Extensions.BondProtocol.API.SpeechRecognitionResult_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.API
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Collections.Generic;
    
    public class SpeechRecognitionResult
    {
        [JsonConverter(typeof(StringEnumConverter))]
        public SpeechRecognitionStatus RecognitionStatus { get; set; }
        
        public List<SpeechRecognizedPhrase> RecognizedPhrases { get; set; }
        
        public ConfusionNetwork ConfusionNetworkData { get; set; }

        public SpeechRecognitionResult()
        {
            RecognitionStatus = SpeechRecognitionStatus.None;
            RecognizedPhrases = new List<SpeechRecognizedPhrase>();
        }
    }
} // Durandal.API
