
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.1.0
//   File : Durandal.Extensions.BondProtocol.API.SpeechRecognitionStatus_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.API
{
    using System.Collections.Generic;
    
    public enum SpeechRecognitionStatus
    {
        None = unchecked((int)0),
        Success = unchecked((int)1),
        NoMatch = unchecked((int)2),
        InitialSilenceTimeout = unchecked((int)3),
        BabbleTimeout = unchecked((int)4),
        Cancelled = unchecked((int)5),
        Error = unchecked((int)6),
    }
} // Durandal.API
