
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.1.0
//   File : Durandal.Extensions.BondProtocol.API.SpeechPhraseElement_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.API
{
    using Durandal.Common.IO.Json;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public class SpeechPhraseElement
    {
        public float SREngineConfidence { get; set; }

        public string IPASyllables { get; set; }

        public string LexicalForm { get; set; }

        public string DisplayText { get; set; }
        
        public string Pronunciation { get; set; }

        [JsonConverter(typeof(JsonTimeSpanTicksConverter))]
        public TimeSpan? AudioTimeOffset { get; set; }

        [JsonConverter(typeof(JsonTimeSpanTicksConverter))]
        public TimeSpan? AudioTimeLength { get; set; }

        public SpeechPhraseElement()
        {
            IPASyllables = string.Empty;
            LexicalForm = string.Empty;
            DisplayText = string.Empty;
            Pronunciation = string.Empty;
        }
    }
} // Durandal.API
