
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.10.0.0
//   File : Durandal.API.SpeechHypothesis_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.API
{
    using System.Collections.Generic;

    public class SpeechHypothesis_v16
    {
        public string Utterance { get; set; }

        public float Confidence { get; set; }

        public string LexicalForm { get; set; }
        
        public SpeechHypothesis_v16()
        {
            Utterance = string.Empty;
            Confidence = 0.0F;
            LexicalForm = string.Empty;
        }
    }
} // Durandal.API
