
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.Remoting.RemoteCrossDomainRequestRequest.bond
//   Output filename: Durandal.BondProtocol.Remoting.RemoteCrossDomainRequestRequest_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.Remoting
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class RemoteCrossDomainRequestRequest
        : RemoteProcedureRequest
    {
        [global::Bond.Id(3), global::Bond.Required]
        public global::Durandal.Extensions.BondProtocol.API.PluginStrongName PluginId { get; set; }

        [global::Bond.Id(4), global::Bond.Required]
        public string TargetIntent { get; set; }

        [global::Bond.Id(5), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string TraceId { get; set; }

        [global::Bond.Id(6)]
        public int ValidLogLevels { get; set; }

        public RemoteCrossDomainRequestRequest()
            : this("Durandal.Extensions.BondProtocol.Remoting.RemoteCrossDomainRequestRequest", "RemoteCrossDomainRequestRequest")
        {}

        protected RemoteCrossDomainRequestRequest(string fullName, string name)
        {
            PluginId = new global::Durandal.Extensions.BondProtocol.API.PluginStrongName();
            TargetIntent = "";
        }
    }
} // Durandal.Extensions.BondProtocol.Remoting
