
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.InstrumentationData.bond
//   Output filename: Durandal.BondProtocol.API.InstrumentationData_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class InstrumentationEvent
    {
        [global::Bond.Id(1), global::Bond.Required]
        public string TraceId { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public string Message { get; set; }

        [global::Bond.Id(3), global::Bond.Required]
        public long Timestamp { get; set; }

        [global::Bond.Id(4), global::Bond.Required]
        public short Level { get; set; }

        [global::Bond.Id(5), global::Bond.Required]
        public string Component { get; set; }

        [global::Bond.Id(6)]
        public ushort PrivacyClassification { get; set; }

        public InstrumentationEvent()
            : this("Durandal.Extensions.BondProtocol.API.InstrumentationEvent", "InstrumentationEvent")
        {}

        protected InstrumentationEvent(string fullName, string name)
        {
            TraceId = "";
            Message = "";
            Component = "";
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class InstrumentationEventList
    {
        [global::Bond.Id(1), global::Bond.Required]
        public List<InstrumentationEvent> Events { get; set; }

        public InstrumentationEventList()
            : this("Durandal.Extensions.BondProtocol.API.InstrumentationEventList", "InstrumentationEventList")
        {}

        protected InstrumentationEventList(string fullName, string name)
        {
            Events = new List<InstrumentationEvent>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class SerializedMetricEvent
    {
        [global::Bond.Id(1), global::Bond.Required]
        public string CounterName { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public string SerializedDimensions { get; set; }

        [global::Bond.Id(3), global::Bond.Required]
        public int MetricType { get; set; }

        [global::Bond.Id(4), global::Bond.Required]
        public System.ArraySegment<byte> SerializedValues { get; set; }

        public SerializedMetricEvent()
            : this("Durandal.Extensions.BondProtocol.API.SerializedMetricEvent", "SerializedMetricEvent")
        {}

        protected SerializedMetricEvent(string fullName, string name)
        {
            CounterName = "";
            SerializedDimensions = "";
            SerializedValues = new System.ArraySegment<byte>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class SerializedMetricEventList
    {
        [global::Bond.Id(1), global::Bond.Required]
        public List<SerializedMetricEvent> Events { get; set; }

        public SerializedMetricEventList()
            : this("Durandal.Extensions.BondProtocol.API.SerializedMetricEventList", "SerializedMetricEventList")
        {}

        protected SerializedMetricEventList(string fullName, string name)
        {
            Events = new List<SerializedMetricEvent>();
        }
    }
} // Durandal.Extensions.BondProtocol.API
