
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.ClientRequest_v17.bond
//   Output filename: Durandal.BondProtocol.API.ClientRequest_v17_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class ClientRequest_v17
    {
        [global::Bond.Id(1), global::Bond.Required]
        public int ProtocolVersion { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public ClientContext ClientContext { get; set; }

        [global::Bond.Id(3), global::Bond.Required]
        public InputMethod InputType { get; set; }

        [global::Bond.Id(4), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string TextInput { get; set; }

        [global::Bond.Id(5), global::Bond.Type(typeof(global::Bond.Tag.nullable<SpeechRecognitionResult>))]
        public SpeechRecognitionResult SpeechInput { get; set; }

        [global::Bond.Id(6), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<SecurityToken>>))]
        public List<SecurityToken> AuthTokens { get; set; }

        [global::Bond.Id(7), global::Bond.Type(typeof(global::Bond.Tag.nullable<AudioData>))]
        public AudioData InputAudio { get; set; }

        [global::Bond.Id(8), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<RecognizedPhrase>>))]
        public List<RecognizedPhrase> LanguageUnderstanding { get; set; }

        [global::Bond.Id(9), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string PreferredAudioCodec { get; set; }

        [global::Bond.Id(10), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string TraceId { get; set; }

        [global::Bond.Id(11), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<string>>))]
        public List<string> DomainScope { get; set; }

        [global::Bond.Id(12), global::Bond.Type(typeof(global::Bond.Tag.nullable<int>))]
        public int? ClientAudioPlaybackTimeMs { get; set; }

        [global::Bond.Id(13)]
        public uint RequestFlags { get; set; }

        public ClientRequest_v17()
            : this("Durandal.Extensions.BondProtocol.API.ClientRequest_v17", "ClientRequest_v17")
        {}

        protected ClientRequest_v17(string fullName, string name)
        {
            ProtocolVersion = 17;
            ClientContext = new ClientContext();
            InputType = InputMethod.Unknown;
            RequestFlags = 0;
        }
    }
} // Durandal.Extensions.BondProtocol.API
