
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.Remoting.RemoteFileCreateDirectoryRequest.bond
//   Output filename: Durandal.BondProtocol.Remoting.RemoteFileCreateDirectoryRequest_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.Remoting
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class RemoteFileCreateDirectoryRequest
        : RemoteProcedureRequest
    {
        [global::Bond.Id(3), global::Bond.Required]
        public string DirectoryPath { get; set; }

        public RemoteFileCreateDirectoryRequest()
            : this("Durandal.Extensions.BondProtocol.Remoting.RemoteFileCreateDirectoryRequest", "RemoteFileCreateDirectoryRequest")
        {}

        protected RemoteFileCreateDirectoryRequest(string fullName, string name)
        {
            DirectoryPath = "";
        }
    }
} // Durandal.Extensions.BondProtocol.Remoting
