
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.Remoting.RemoteFileStreamSeekRequest.bond
//   Output filename: Durandal.BondProtocol.Remoting.RemoteFileStreamSeekRequest_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.Remoting
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class RemoteFileStreamSeekRequest
        : RemoteProcedureRequest
    {
        [global::Bond.Id(3), global::Bond.Required]
        public string StreamId { get; set; }

        [global::Bond.Id(4), global::Bond.Required]
        public RemoteFileStreamSeekOrigin Origin { get; set; }

        [global::Bond.Id(5), global::Bond.Required]
        public long Offset { get; set; }

        public RemoteFileStreamSeekRequest()
            : this("Durandal.Extensions.BondProtocol.Remoting.RemoteFileStreamSeekRequest", "RemoteFileStreamSeekRequest")
        {}

        protected RemoteFileStreamSeekRequest(string fullName, string name)
        {
            StreamId = "";
            Origin = RemoteFileStreamSeekOrigin.Unknown;
        }
    }
} // Durandal.Extensions.BondProtocol.Remoting
