
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.DialogProcessingResponse.bond
//   Output filename: Durandal.BondProtocol.API.DialogProcessingResponse_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class DialogProcessingResponse
    {
        [global::Bond.Id(1), global::Bond.Type(typeof(global::Bond.Tag.nullable<PluginResult>))]
        public PluginResult PluginOutput { get; set; }

        [global::Bond.Id(2)]
        public bool WasRetrying { get; set; }

        [global::Bond.Id(3), global::Bond.Type(typeof(global::Bond.Tag.nullable<InMemoryDataStore>))]
        public InMemoryDataStore UpdatedSessionStore { get; set; }

        [global::Bond.Id(4), global::Bond.Type(typeof(global::Bond.Tag.nullable<InMemoryDataStore>))]
        public InMemoryDataStore UpdatedLocalProfile { get; set; }

        [global::Bond.Id(5), global::Bond.Type(typeof(global::Bond.Tag.nullable<InMemoryDataStore>))]
        public InMemoryDataStore UpdatedGlobalProfile { get; set; }

        [global::Bond.Id(6), global::Bond.Type(typeof(global::Bond.Tag.nullable<System.ArraySegment<byte>>))]
        public System.ArraySegment<byte> UpdatedEntityContext { get; set; }

        [global::Bond.Id(7), global::Bond.Type(typeof(global::Bond.Tag.nullable<System.ArraySegment<byte>>))]
        public System.ArraySegment<byte> UpdatedEntityHistory { get; set; }

        [global::Bond.Id(8), global::Bond.Type(typeof(global::Bond.Tag.nullable<InMemoryDialogActionCache>))]
        public InMemoryDialogActionCache UpdatedDialogActions { get; set; }

        [global::Bond.Id(9), global::Bond.Type(typeof(global::Bond.Tag.nullable<InMemoryWebDataCache>))]
        public InMemoryWebDataCache UpdatedWebDataCache { get; set; }

        public DialogProcessingResponse()
            : this("Durandal.Extensions.BondProtocol.API.DialogProcessingResponse", "DialogProcessingResponse")
        {}

        protected DialogProcessingResponse(string fullName, string name)
        {
            WasRetrying = false;
        }
    }
} // Durandal.Extensions.BondProtocol.API
