
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.InMemoryDataStore.bond
//   Output filename: Durandal.BondProtocol.API.InMemoryDataStore_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class InMemoryDataStoreItem
    {
        [global::Bond.Id(1), global::Bond.Required]
        public string Key { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public System.ArraySegment<byte> Value { get; set; }

        public InMemoryDataStoreItem()
            : this("Durandal.Extensions.BondProtocol.API.InMemoryDataStoreItem", "InMemoryDataStoreItem")
        {}

        protected InMemoryDataStoreItem(string fullName, string name)
        {
            Key = "";
            Value = new System.ArraySegment<byte>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class InMemoryDataStore
    {
        [global::Bond.Id(1)]
        public List<InMemoryDataStoreItem> Items { get; set; }

        public InMemoryDataStore()
            : this("Durandal.Extensions.BondProtocol.API.InMemoryDataStore", "InMemoryDataStore")
        {}

        protected InMemoryDataStore(string fullName, string name)
        {
            Items = new List<InMemoryDataStoreItem>();
        }
    }
} // Durandal.Extensions.BondProtocol.API
