
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.LURequest.bond
//   Output filename: Durandal.BondProtocol.API.LURequest_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class LURequest
    {
        [global::Bond.Id(1), global::Bond.Required]
        public int ProtocolVersion { get; set; }

        [global::Bond.Id(2), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string TextInput { get; set; }

        [global::Bond.Id(3), global::Bond.Type(typeof(global::Bond.Tag.nullable<SpeechRecognitionResult>))]
        public SpeechRecognitionResult SpeechInput { get; set; }

        [global::Bond.Id(4), global::Bond.Required]
        public ClientContext Context { get; set; }

        [global::Bond.Id(5)]
        public bool DoFullAnnotation { get; set; }

        [global::Bond.Id(6)]
        public string TraceId { get; set; }

        [global::Bond.Id(7)]
        public List<string> DomainScope { get; set; }

        [global::Bond.Id(8)]
        public uint RequestFlags { get; set; }

        [global::Bond.Id(9)]
        public List<string> ContextualDomains { get; set; }

        public LURequest()
            : this("Durandal.Extensions.BondProtocol.API.LURequest", "LURequest")
        {}

        protected LURequest(string fullName, string name)
        {
            ProtocolVersion = 20;
            Context = new ClientContext();
            DoFullAnnotation = true;
            TraceId = "";
            DomainScope = new List<string>();
            RequestFlags = 0;
            ContextualDomains = new List<string>();
        }
    }
} // Durandal.Extensions.BondProtocol.API
