
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.LoadedPluginInformation.bond
//   Output filename: Durandal.BondProtocol.API.LoadedPluginInformation_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class LoadedPluginInformation
    {
        [global::Bond.Id(1), global::Bond.Required]
        public PluginStrongName PluginStrongName { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public string LUDomain { get; set; }

        [global::Bond.Id(3), global::Bond.Required]
        public string PluginId { get; set; }

        [global::Bond.Id(4), global::Bond.Type(typeof(global::Bond.Tag.nullable<PluginInformation>))]
        public PluginInformation PluginInfo { get; set; }

        [global::Bond.Id(5), global::Bond.Type(typeof(global::Bond.Tag.nullable<SerializedConversationTree>))]
        public SerializedConversationTree SerializedConversationTree { get; set; }

        public LoadedPluginInformation()
            : this("Durandal.Extensions.BondProtocol.API.LoadedPluginInformation", "LoadedPluginInformation")
        {}

        protected LoadedPluginInformation(string fullName, string name)
        {
            PluginStrongName = new PluginStrongName();
            LUDomain = "";
            PluginId = "";
        }
    }
} // Durandal.Extensions.BondProtocol.API
