
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.Remoting.RemoteFileStat.bond
//   Output filename: Durandal.BondProtocol.Remoting.RemoteFileStat_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.Remoting
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class RemoteFileStat
    {
        [global::Bond.Id(1), global::Bond.Required]
        public bool Exists { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public bool IsDirectory { get; set; }

        [global::Bond.Id(3), global::Bond.Type(typeof(global::Bond.Tag.nullable<long>))]
        public long? LastWriteTime { get; set; }

        [global::Bond.Id(4), global::Bond.Type(typeof(global::Bond.Tag.nullable<long>))]
        public long? CreationTime { get; set; }

        [global::Bond.Id(5), global::Bond.Type(typeof(global::Bond.Tag.nullable<long>))]
        public long? LastAccessTime { get; set; }

        [global::Bond.Id(6)]
        public long Size { get; set; }

        public RemoteFileStat()
            : this("Durandal.Extensions.BondProtocol.Remoting.RemoteFileStat", "RemoteFileStat")
        {}

        protected RemoteFileStat(string fullName, string name)
        {
            
        }
    }
} // Durandal.Extensions.BondProtocol.Remoting
