
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.MultiTurnBehavior.bond
//   Output filename: Durandal.BondProtocol.API.MultiTurnBehavior_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class MultiTurnBehavior
    {
        [global::Bond.Id(1), global::Bond.Required]
        public bool Continues { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public bool IsImmediate { get; set; }

        [global::Bond.Id(3)]
        public int SuggestedPauseDelay { get; set; }

        [global::Bond.Id(4)]
        public int ConversationTimeoutSeconds { get; set; }

        [global::Bond.Id(5)]
        public bool FullConversationControl { get; set; }

        public MultiTurnBehavior()
            : this("Durandal.Extensions.BondProtocol.API.MultiTurnBehavior", "MultiTurnBehavior")
        {}

        protected MultiTurnBehavior(string fullName, string name)
        {
            ConversationTimeoutSeconds = 60;
            FullConversationControl = false;
        }
    }
} // Durandal.Extensions.BondProtocol.API
