
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.SerializedConversationState.bond
//   Output filename: Durandal.BondProtocol.API.SerializedConversationState_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class SerializedConversationState
    {
        [global::Bond.Id(1), global::Bond.Required]
        public int TurnNum { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public int RetryNum { get; set; }

        [global::Bond.Id(3), global::Bond.Required]
        public List<RecoResult> PreviousConversationTurns { get; set; }

        [global::Bond.Id(4), global::Bond.Required]
        public string CurrentPluginDomain { get; set; }

        [global::Bond.Id(5), global::Bond.Required]
        public MultiTurnBehavior LastMultiturnState { get; set; }

        [global::Bond.Id(6), global::Bond.Required]
        public string CurrentConversationNode { get; set; }

        [global::Bond.Id(7), global::Bond.Required]
        public long ConversationExpireTime { get; set; }

        [global::Bond.Id(8)]
        public InMemoryDataStore SessionStore { get; set; }

        [global::Bond.Id(9)]
        public string NextContinuationFuncName { get; set; }

        [global::Bond.Id(10)]
        public string CurrentPluginId { get; set; }

        [global::Bond.Id(11)]
        public int CurrentPluginVersionMajor { get; set; }

        [global::Bond.Id(12)]
        public int CurrentPluginVersionMinor { get; set; }

        public SerializedConversationState()
            : this("Durandal.Extensions.BondProtocol.API.SerializedConversationState", "SerializedConversationState")
        {}

        protected SerializedConversationState(string fullName, string name)
        {
            TurnNum = 0;
            RetryNum = 0;
            CurrentPluginDomain = "";
            LastMultiturnState = new MultiTurnBehavior();
            CurrentConversationNode = "";
            ConversationExpireTime = 0;
            SessionStore = new InMemoryDataStore();
            NextContinuationFuncName = "";
            CurrentPluginId = "";
            CurrentPluginVersionMajor = 0;
            CurrentPluginVersionMinor = 0;
        }
    }
} // Durandal.Extensions.BondProtocol.API
