
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.ConfusionNetwork.bond
//   Output filename: Durandal.BondProtocol.API.ConfusionNetwork_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class ConfusionNetwork
    {
        [global::Bond.Id(1)]
        public List<string> WordTable { get; set; }

        [global::Bond.Id(2)]
        public List<ConfusionNetworkNode> Nodes { get; set; }

        [global::Bond.Id(3)]
        public List<ConfusionNetworkArc> Arcs { get; set; }

        [global::Bond.Id(4)]
        public List<ushort> BestArcsIndexes { get; set; }

        public ConfusionNetwork()
            : this("Durandal.Extensions.BondProtocol.API.ConfusionNetwork", "ConfusionNetwork")
        {}

        protected ConfusionNetwork(string fullName, string name)
        {
            WordTable = new List<string>();
            Nodes = new List<ConfusionNetworkNode>();
            Arcs = new List<ConfusionNetworkArc>();
            BestArcsIndexes = new List<ushort>();
        }
    }
} // Durandal.Extensions.BondProtocol.API
