
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.SpeechRecognizedPhrase.bond
//   Output filename: Durandal.BondProtocol.API.SpeechRecognizedPhrase_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class SpeechRecognizedPhrase
    {
        [global::Bond.Id(1)]
        public string DisplayText { get; set; }

        [global::Bond.Id(2)]
        public string LexicalForm { get; set; }

        [global::Bond.Id(3)]
        public float SREngineConfidence { get; set; }

        [global::Bond.Id(4), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<SpeechPhraseElement>>))]
        public List<SpeechPhraseElement> PhraseElements { get; set; }

        [global::Bond.Id(5)]
        public string Locale { get; set; }

        [global::Bond.Id(6)]
        public uint AudioTimeOffset { get; set; }

        [global::Bond.Id(7)]
        public uint AudioTimeLength { get; set; }

        [global::Bond.Id(8), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<string>>))]
        public List<string> InverseTextNormalizationResults { get; set; }

        [global::Bond.Id(9), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<Tag>>))]
        public List<Tag> ProfanityTags { get; set; }

        [global::Bond.Id(10), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<string>>))]
        public List<string> MaskedInverseTextNormalizationResults { get; set; }

        public SpeechRecognizedPhrase()
            : this("Durandal.Extensions.BondProtocol.API.SpeechRecognizedPhrase", "SpeechRecognizedPhrase")
        {}

        protected SpeechRecognizedPhrase(string fullName, string name)
        {
            DisplayText = "";
            LexicalForm = "";
            Locale = "";
        }
    }
} // Durandal.Extensions.BondProtocol.API
