
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.ContextualEntity.bond
//   Output filename: Durandal.BondProtocol.API.ContextualEntity_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class ContextualEntity
    {
        [global::Bond.Id(1), global::Bond.Required]
        public string EntityId { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public float Relevance { get; set; }

        [global::Bond.Id(3)]
        public ContextualEntitySource Source { get; set; }

        public ContextualEntity()
            : this("Durandal.Extensions.BondProtocol.API.ContextualEntity", "ContextualEntity")
        {}

        protected ContextualEntity(string fullName, string name)
        {
            EntityId = "";
            Source = ContextualEntitySource.Unknown;
        }
    }
} // Durandal.Extensions.BondProtocol.API
