
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.Remoting.RemoteInt64Response.bond
//   Output filename: Durandal.BondProtocol.Remoting.RemoteInt64Response_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.Remoting
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class RemoteInt64Response
        : RemoteProcedureResponse
    {
        [global::Bond.Id(4)]
        public long ReturnVal { get; set; }

        public RemoteInt64Response()
            : this("Durandal.Extensions.BondProtocol.Remoting.RemoteInt64Response", "RemoteInt64Response")
        {}

        protected RemoteInt64Response(string fullName, string name)
        {
            
        }
    }
} // Durandal.Extensions.BondProtocol.Remoting
