
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.Remoting.RemoteException.bond
//   Output filename: Durandal.BondProtocol.Remoting.RemoteException_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.Remoting
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class RemoteException
    {
        [global::Bond.Id(1)]
        public string ExceptionType { get; set; }

        [global::Bond.Id(2)]
        public string Message { get; set; }

        [global::Bond.Id(3)]
        public string StackTrace { get; set; }

        public RemoteException()
            : this("Durandal.Extensions.BondProtocol.Remoting.RemoteException", "RemoteException")
        {}

        protected RemoteException(string fullName, string name)
        {
            ExceptionType = "";
            Message = "";
            StackTrace = "";
        }
    }
} // Durandal.Extensions.BondProtocol.Remoting
