
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.SerializedConversationTree.bond
//   Output filename: Durandal.BondProtocol.API.SerializedConversationTree_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class SerializedConversationEdge
    {
        [global::Bond.Id(1), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string Intent { get; set; }

        [global::Bond.Id(2), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string TargetNodeName { get; set; }

        [global::Bond.Id(3)]
        public DomainScope Scope { get; set; }

        [global::Bond.Id(4), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string ExternalDomain { get; set; }

        [global::Bond.Id(5), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string ExternalIntent { get; set; }

        public SerializedConversationEdge()
            : this("Durandal.Extensions.BondProtocol.API.SerializedConversationEdge", "SerializedConversationEdge")
        {}

        protected SerializedConversationEdge(string fullName, string name)
        {
            Scope = DomainScope.Local;
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class SerializedConversationNode
    {
        [global::Bond.Id(1), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string NodeName { get; set; }

        [global::Bond.Id(2), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string HandlerFunction { get; set; }

        [global::Bond.Id(3), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string RetryHandler { get; set; }

        [global::Bond.Id(4)]
        public List<SerializedConversationEdge> Edges { get; set; }

        public SerializedConversationNode()
            : this("Durandal.Extensions.BondProtocol.API.SerializedConversationNode", "SerializedConversationNode")
        {}

        protected SerializedConversationNode(string fullName, string name)
        {
            Edges = new List<SerializedConversationEdge>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class SerializedConversationTree
    {
        [global::Bond.Id(1), global::Bond.Required]
        public string LocalDomain { get; set; }

        [global::Bond.Id(2)]
        public List<SerializedConversationNode> Nodes { get; set; }

        public SerializedConversationTree()
            : this("Durandal.Extensions.BondProtocol.API.SerializedConversationTree", "SerializedConversationTree")
        {}

        protected SerializedConversationTree(string fullName, string name)
        {
            LocalDomain = "";
            Nodes = new List<SerializedConversationNode>();
        }
    }
} // Durandal.Extensions.BondProtocol.API
