
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.OAuthConfig.bond
//   Output filename: Durandal.BondProtocol.API.OAuthConfig_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class OAuthConfig
    {
        [global::Bond.Id(1), global::Bond.Required]
        public OAuthFlavor Type { get; set; }

        [global::Bond.Id(2), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string ConfigName { get; set; }

        [global::Bond.Id(3), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string ClientId { get; set; }

        [global::Bond.Id(4), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string ClientSecret { get; set; }

        [global::Bond.Id(5), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string TokenUri { get; set; }

        [global::Bond.Id(6), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string AuthUri { get; set; }

        [global::Bond.Id(7), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string Scope { get; set; }

        [global::Bond.Id(8)]
        public bool UsePKCE { get; set; }

        [global::Bond.Id(9), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string AuthorizationHeader { get; set; }

        public OAuthConfig()
            : this("Durandal.Extensions.BondProtocol.API.OAuthConfig", "OAuthConfig")
        {}

        protected OAuthConfig(string fullName, string name)
        {
            Type = OAuthFlavor.OAuth2;
        }
    }
} // Durandal.Extensions.BondProtocol.API
