
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.InMemoryWebDataCache.bond
//   Output filename: Durandal.BondProtocol.API.InMemoryWebDataCache_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class InMemoryCachedWebData
    {
        [global::Bond.Id(1), global::Bond.Required]
        public string Key { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public CachedWebData Value { get; set; }

        [global::Bond.Id(3), global::Bond.Type(typeof(global::Bond.Tag.nullable<int>))]
        public int? LifeTimeSeconds { get; set; }

        [global::Bond.Id(4), global::Bond.Type(typeof(global::Bond.Tag.nullable<long>))]
        public long? ExpireTimeUtcTicks { get; set; }

        public InMemoryCachedWebData()
            : this("Durandal.Extensions.BondProtocol.API.InMemoryCachedWebData", "InMemoryCachedWebData")
        {}

        protected InMemoryCachedWebData(string fullName, string name)
        {
            Key = "";
            Value = new CachedWebData();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class InMemoryWebDataCache
    {
        [global::Bond.Id(1)]
        public List<InMemoryCachedWebData> Items { get; set; }

        public InMemoryWebDataCache()
            : this("Durandal.Extensions.BondProtocol.API.InMemoryWebDataCache", "InMemoryWebDataCache")
        {}

        protected InMemoryWebDataCache(string fullName, string name)
        {
            Items = new List<InMemoryCachedWebData>();
        }
    }
} // Durandal.Extensions.BondProtocol.API
