
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.ProtocolVersionHeader.bond
//   Output filename: Durandal.BondProtocol.API.ProtocolVersionHeader_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class ProtocolVersionHeader
    {
        [global::Bond.Id(1), global::Bond.Required]
        public int ProtocolVersion { get; set; }

        public ProtocolVersionHeader()
            : this("Durandal.Extensions.BondProtocol.API.ProtocolVersionHeader", "ProtocolVersionHeader")
        {}

        protected ProtocolVersionHeader(string fullName, string name)
        {
            ProtocolVersion = 20;
        }
    }
} // Durandal.Extensions.BondProtocol.API
