
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.Remoting.RemoteCrossDomainResponseRequest.bond
//   Output filename: Durandal.BondProtocol.Remoting.RemoteCrossDomainResponseRequest_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.Remoting
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class RemoteCrossDomainResponseRequest
        : RemoteProcedureRequest
    {
        [global::Bond.Id(3), global::Bond.Required]
        public global::Durandal.Extensions.BondProtocol.API.PluginStrongName PluginId { get; set; }

        [global::Bond.Id(4), global::Bond.Required]
        public global::Durandal.Extensions.BondProtocol.API.CrossDomainContext Context { get; set; }

        [global::Bond.Id(5), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string TraceId { get; set; }

        [global::Bond.Id(6)]
        public int ValidLogLevels { get; set; }

        [global::Bond.Id(7), global::Bond.Type(typeof(global::Bond.Tag.nullable<global::Durandal.Extensions.BondProtocol.API.InMemoryDataStore>))]
        public global::Durandal.Extensions.BondProtocol.API.InMemoryDataStore SessionStore { get; set; }

        public RemoteCrossDomainResponseRequest()
            : this("Durandal.Extensions.BondProtocol.Remoting.RemoteCrossDomainResponseRequest", "RemoteCrossDomainResponseRequest")
        {}

        protected RemoteCrossDomainResponseRequest(string fullName, string name)
        {
            PluginId = new global::Durandal.Extensions.BondProtocol.API.PluginStrongName();
            Context = new global::Durandal.Extensions.BondProtocol.API.CrossDomainContext();
        }
    }
} // Durandal.Extensions.BondProtocol.Remoting
