
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.Remoting.RemoteExecutePluginRequest.bond
//   Output filename: Durandal.BondProtocol.Remoting.RemoteExecutePluginRequest_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.Remoting
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class RemoteExecutePluginRequest
        : RemoteProcedureRequest
    {
        [global::Bond.Id(3), global::Bond.Required]
        public global::Durandal.Extensions.BondProtocol.API.PluginStrongName PluginId { get; set; }

        [global::Bond.Id(4), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string EntryPoint { get; set; }

        [global::Bond.Id(5)]
        public bool IsRetry { get; set; }

        [global::Bond.Id(6)]
        public global::Durandal.Extensions.BondProtocol.API.QueryWithContext Query { get; set; }

        [global::Bond.Id(7), global::Bond.Type(typeof(global::Bond.Tag.nullable<global::Durandal.Extensions.BondProtocol.API.InMemoryDataStore>))]
        public global::Durandal.Extensions.BondProtocol.API.InMemoryDataStore SessionStore { get; set; }

        [global::Bond.Id(8), global::Bond.Type(typeof(global::Bond.Tag.nullable<global::Durandal.Extensions.BondProtocol.API.InMemoryDataStore>))]
        public global::Durandal.Extensions.BondProtocol.API.InMemoryDataStore LocalUserProfile { get; set; }

        [global::Bond.Id(9), global::Bond.Type(typeof(global::Bond.Tag.nullable<global::Durandal.Extensions.BondProtocol.API.InMemoryDataStore>))]
        public global::Durandal.Extensions.BondProtocol.API.InMemoryDataStore GlobalUserProfile { get; set; }

        [global::Bond.Id(10), global::Bond.Type(typeof(global::Bond.Tag.nullable<System.ArraySegment<byte>>))]
        public System.ArraySegment<byte> EntityContext { get; set; }

        [global::Bond.Id(11), global::Bond.Type(typeof(global::Bond.Tag.nullable<System.ArraySegment<byte>>))]
        public System.ArraySegment<byte> EntityHistory { get; set; }

        [global::Bond.Id(12), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<global::Durandal.Extensions.BondProtocol.API.ContextualEntity>>))]
        public List<global::Durandal.Extensions.BondProtocol.API.ContextualEntity> ContextualEntities { get; set; }

        [global::Bond.Id(13), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string TraceId { get; set; }

        [global::Bond.Id(14)]
        public int ValidLogLevels { get; set; }

        [global::Bond.Id(15)]
        public bool GlobalUserProfileIsWritable { get; set; }

        public RemoteExecutePluginRequest()
            : this("Durandal.Extensions.BondProtocol.Remoting.RemoteExecutePluginRequest", "RemoteExecutePluginRequest")
        {}

        protected RemoteExecutePluginRequest(string fullName, string name)
        {
            PluginId = new global::Durandal.Extensions.BondProtocol.API.PluginStrongName();
            Query = new global::Durandal.Extensions.BondProtocol.API.QueryWithContext();
        }
    }
} // Durandal.Extensions.BondProtocol.Remoting
