
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.QueryWithContext.bond
//   Output filename: Durandal.BondProtocol.API.QueryWithContext_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class QueryWithContext
    {
        [global::Bond.Id(1), global::Bond.Required]
        public RecoResult Understanding { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public List<RecoResult> PastTurns { get; set; }

        [global::Bond.Id(3), global::Bond.Required]
        public int TurnNum { get; set; }

        [global::Bond.Id(4), global::Bond.Required]
        public ClientContext ClientContext { get; set; }

        [global::Bond.Id(5), global::Bond.Required]
        public ClientAuthenticationLevel AuthenticationLevel { get; set; }

        [global::Bond.Id(6), global::Bond.Required]
        public InputMethod Source { get; set; }

        [global::Bond.Id(7), global::Bond.Type(typeof(global::Bond.Tag.nullable<AudioData>))]
        public AudioData InputAudio { get; set; }

        [global::Bond.Id(8)]
        public int RetryCount { get; set; }

        [global::Bond.Id(9), global::Bond.Type(typeof(global::Bond.Tag.nullable<int>))]
        public int? BargeInTimeMs { get; set; }

        [global::Bond.Id(10)]
        public ClientAuthenticationScope AuthScope { get; set; }

        [global::Bond.Id(11)]
        public uint RequestFlags { get; set; }

        [global::Bond.Id(12), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string OriginalTextInput { get; set; }

        [global::Bond.Id(13), global::Bond.Type(typeof(global::Bond.Tag.nullable<SpeechRecognitionResult>))]
        public SpeechRecognitionResult OriginalSpeechInput { get; set; }

        [global::Bond.Id(14), global::Bond.Type(typeof(global::Bond.Tag.nullable<Dictionary<string, string>>))]
        public Dictionary<string, string> RequestData { get; set; }

        public QueryWithContext()
            : this("Durandal.Extensions.BondProtocol.API.QueryWithContext", "QueryWithContext")
        {}

        protected QueryWithContext(string fullName, string name)
        {
            Understanding = new RecoResult();
            PastTurns = new List<RecoResult>();
            ClientContext = new ClientContext();
            AuthenticationLevel = ClientAuthenticationLevel.None;
            Source = InputMethod.Unknown;
            AuthScope = ClientAuthenticationScope.None;
            RequestFlags = 0;
        }
    }
} // Durandal.Extensions.BondProtocol.API
