
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.CachedWebData.bond
//   Output filename: Durandal.BondProtocol.API.CachedWebData_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class CachedWebData
    {
        [global::Bond.Id(1), global::Bond.Required]
        public System.ArraySegment<byte> Data { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public string MimeType { get; set; }

        [global::Bond.Id(3)]
        public int LifetimeSeconds { get; set; }

        [global::Bond.Id(4), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string TraceId { get; set; }

        public CachedWebData()
            : this("Durandal.Extensions.BondProtocol.API.CachedWebData", "CachedWebData")
        {}

        protected CachedWebData(string fullName, string name)
        {
            Data = new System.ArraySegment<byte>();
            MimeType = "";
        }
    }
} // Durandal.Extensions.BondProtocol.API
