
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.ConfusionNetworkArc.bond
//   Output filename: Durandal.BondProtocol.API.ConfusionNetworkArc_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class ConfusionNetworkArc
    {
        [global::Bond.Id(1)]
        public ushort PreviousNodeIndex { get; set; }

        [global::Bond.Id(2)]
        public ushort NextNodeIndex { get; set; }

        [global::Bond.Id(3)]
        public uint WordStartIndex { get; set; }

        [global::Bond.Id(4)]
        public float Score { get; set; }

        [global::Bond.Id(5)]
        public bool IsLastArc { get; set; }

        public ConfusionNetworkArc()
            : this("Durandal.Extensions.BondProtocol.API.ConfusionNetworkArc", "ConfusionNetworkArc")
        {}

        protected ConfusionNetworkArc(string fullName, string name)
        {
            
        }
    }
} // Durandal.Extensions.BondProtocol.API
