
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.CrossDomainContext.bond
//   Output filename: Durandal.BondProtocol.API.CrossDomainContext_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class CrossDomainContext
    {
        [global::Bond.Id(1), global::Bond.Required]
        public string RequestDomain { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public string RequestIntent { get; set; }

        [global::Bond.Id(3), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<CrossDomainSlot>>))]
        public List<CrossDomainSlot> RequestedSlots { get; set; }

        [global::Bond.Id(4), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<RecoResult>>))]
        public List<RecoResult> PastConversationTurns { get; set; }

        public CrossDomainContext()
            : this("Durandal.Extensions.BondProtocol.API.CrossDomainContext", "CrossDomainContext")
        {}

        protected CrossDomainContext(string fullName, string name)
        {
            RequestDomain = "";
            RequestIntent = "";
        }
    }
} // Durandal.Extensions.BondProtocol.API
