
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.AudioResponse.bond
//   Output filename: Durandal.BondProtocol.API.AudioResponse_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class AudioResponse
    {
        [global::Bond.Id(1), global::Bond.Required]
        public AudioData Data { get; set; }

        [global::Bond.Id(2)]
        public AudioOrdering Ordering { get; set; }

        public AudioResponse()
            : this("Durandal.Extensions.BondProtocol.API.AudioResponse", "AudioResponse")
        {}

        protected AudioResponse(string fullName, string name)
        {
            Data = new AudioData();
            Ordering = AudioOrdering.AfterSpeech;
        }
    }
} // Durandal.Extensions.BondProtocol.API
