
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.PluginResult.bond
//   Output filename: Durandal.BondProtocol.API.PluginResult_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class PluginResult
    {
        [global::Bond.Id(1), global::Bond.Required]
        public Result ResponseCode { get; set; }

        [global::Bond.Id(2), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string ResponseText { get; set; }

        [global::Bond.Id(3), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string ResponseSsml { get; set; }

        [global::Bond.Id(4), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string ResponseUrl { get; set; }

        [global::Bond.Id(5), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string ResponseHtml { get; set; }

        [global::Bond.Id(6), global::Bond.Type(typeof(global::Bond.Tag.nullable<MultiTurnBehavior>))]
        public MultiTurnBehavior MultiTurnResult { get; set; }

        [global::Bond.Id(7), global::Bond.Type(typeof(global::Bond.Tag.nullable<AudioResponse>))]
        public AudioResponse ResponseAudio { get; set; }

        [global::Bond.Id(8), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string ErrorMessage { get; set; }

        [global::Bond.Id(9), global::Bond.Type(typeof(global::Bond.Tag.nullable<Dictionary<string, string>>))]
        public Dictionary<string, string> ResponseData { get; set; }

        [global::Bond.Id(10), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string ResultConversationNode { get; set; }

        [global::Bond.Id(11), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string ClientAction { get; set; }

        [global::Bond.Id(12), global::Bond.Type(typeof(global::Bond.Tag.nullable<DialogAction>))]
        public DialogAction InvokedDialogAction { get; set; }

        [global::Bond.Id(13), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<string>>))]
        public List<string> SuggestedQueries { get; set; }

        [global::Bond.Id(14), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<TriggerKeyword>>))]
        public List<TriggerKeyword> TriggerKeywords { get; set; }

        [global::Bond.Id(15), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string ContinuationFuncName { get; set; }

        [global::Bond.Id(16), global::Bond.Type(typeof(global::Bond.Tag.nullable<string>))]
        public string AugmentedQuery { get; set; }

        [global::Bond.Id(17), global::Bond.Type(typeof(global::Bond.Tag.nullable<ushort>))]
        public ushort? ResponsePrivacyClassification { get; set; }

        public PluginResult()
            : this("Durandal.Extensions.BondProtocol.API.PluginResult", "PluginResult")
        {}

        protected PluginResult(string fullName, string name)
        {
            ResponseCode = Result.Failure;
        }
    }
} // Durandal.Extensions.BondProtocol.API
