
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.PluginInformation.bond
//   Output filename: Durandal.BondProtocol.API.PluginInformation_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class LocalizedInformation
    {
        [global::Bond.Id(1)]
        public string DisplayName { get; set; }

        [global::Bond.Id(2)]
        public string Creator { get; set; }

        [global::Bond.Id(3)]
        public string ShortDescription { get; set; }

        [global::Bond.Id(4)]
        public List<string> SampleQueries { get; set; }

        public LocalizedInformation()
            : this("Durandal.Extensions.BondProtocol.API.LocalizedInformation", "LocalizedInformation")
        {}

        protected LocalizedInformation(string fullName, string name)
        {
            DisplayName = "";
            Creator = "";
            ShortDescription = "";
            SampleQueries = new List<string>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class PluginInformation
    {
        [global::Bond.Id(1), global::Bond.Required]
        public string InternalName { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public ushort MajorVersion { get; set; }

        [global::Bond.Id(3), global::Bond.Required]
        public ushort MinorVersion { get; set; }

        [global::Bond.Id(4)]
        public string Creator { get; set; }

        [global::Bond.Id(5)]
        public Dictionary<string, LocalizedInformation> LocalizedInfo { get; set; }

        [global::Bond.Id(6)]
        public System.ArraySegment<byte> IconPngData { get; set; }

        [global::Bond.Id(7)]
        public bool Hidden { get; set; }

        [global::Bond.Id(8)]
        public bool Configurable { get; set; }

        public PluginInformation()
            : this("Durandal.Extensions.BondProtocol.API.PluginInformation", "PluginInformation")
        {}

        protected PluginInformation(string fullName, string name)
        {
            InternalName = "";
            Creator = "";
            LocalizedInfo = new Dictionary<string, LocalizedInformation>();
            IconPngData = new System.ArraySegment<byte>();
            Hidden = false;
            Configurable = false;
        }
    }
} // Durandal.Extensions.BondProtocol.API
