
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.Remoting.RemoteFileStreamShareMode.bond
//   Output filename: Durandal.BondProtocol.Remoting.RemoteFileStreamShareMode_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.Remoting
{
    using System.Collections.Generic;

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public enum RemoteFileStreamShareMode
    {
        None = unchecked((int)0),
        Read = unchecked((int)1),
        Write = unchecked((int)2),
        ReadWrite = unchecked((int)3),
        Delete = unchecked((int)4),
    }
} // Durandal.Extensions.BondProtocol.Remoting
