
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.SpeechRecognitionResult.bond
//   Output filename: Durandal.BondProtocol.API.SpeechRecognitionResult_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class SpeechRecognitionResult
    {
        [global::Bond.Id(1)]
        public SpeechRecognitionStatus RecognitionStatus { get; set; }

        [global::Bond.Id(2)]
        public List<SpeechRecognizedPhrase> RecognizedPhrases { get; set; }

        [global::Bond.Id(3), global::Bond.Type(typeof(global::Bond.Tag.nullable<ConfusionNetwork>))]
        public ConfusionNetwork ConfusionNetworkData { get; set; }

        public SpeechRecognitionResult()
            : this("Durandal.Extensions.BondProtocol.API.SpeechRecognitionResult", "SpeechRecognitionResult")
        {}

        protected SpeechRecognitionResult(string fullName, string name)
        {
            RecognitionStatus = SpeechRecognitionStatus.None;
            RecognizedPhrases = new List<SpeechRecognizedPhrase>();
        }
    }
} // Durandal.Extensions.BondProtocol.API
