
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.12.1.0
//   Input filename:  .\Durandal.BondProtocol.API.SlotValue.bond
//   Output filename: Durandal.BondProtocol.API.SlotValue_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Durandal.Extensions.BondProtocol.API
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.12.1.0")]
    public partial class SlotValue
    {
        [global::Bond.Id(1), global::Bond.Required]
        public string Name { get; set; }

        [global::Bond.Id(2), global::Bond.Required]
        public string Value { get; set; }

        [global::Bond.Id(3), global::Bond.Required]
        public SlotValueFormat Format { get; set; }

        [global::Bond.Id(4), global::Bond.Required]
        public Dictionary<string, string> Annotations { get; set; }

        [global::Bond.Id(5), global::Bond.Type(typeof(global::Bond.Tag.nullable<List<string>>))]
        public List<string> Alternates { get; set; }

        [global::Bond.Id(6)]
        public string LexicalForm { get; set; }

        public SlotValue()
            : this("Durandal.Extensions.BondProtocol.API.SlotValue", "SlotValue")
        {}

        protected SlotValue(string fullName, string name)
        {
            Name = "";
            Value = "";
            Format = SlotValueFormat.TypedText;
            Annotations = new Dictionary<string, string>();
            LexicalForm = "";
        }
    }
} // Durandal.Extensions.BondProtocol.API
