using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Durandal.Common.NLP.Train
{
    /// <summary>
    /// Represents an infinite stream of training data that is being generated by an LU training data file of some sort
    /// </summary>
    public interface ITrainingDataStream : IEnumerator<TrainingUtterance>
    {
        int RecommendedOutputCount { get; }
    }
}
