#! /bin/sh     
# /etc/init.d/durandal

### BEGIN INIT INFO
# Provides:          durandal
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     3 5
# Default-Stop:      0 2 1 6
# Short-Description: Durandal client daemon
# Description:       Durandal client daemon
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Durandal service"
   start-stop-daemon -m /var/run/durandal.pid -p /var/run/durandal.pid -b --quiet --start --exec /home/pi/durandal/run.sh
    ;;
  stop)
    echo "Stopping Durandal service"
     #kill 'cat /var/run/durandal.pid' || true
     killall mono
     rm -f /var/run/durandal.pid
    ;;
  *)
    echo "Usage: /etc/init.d/durandal {start|stop}"
    exit 1
    ;;
esac

 exit 0
