



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.not
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : org\stromberg\durandal\api\ClientResponse.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package org.stromberg.durandal.api;


/**
* ClientResponse
*/
@SuppressWarnings("all")
public class ClientResponse implements com.microsoft.bond.BondSerializable, com.microsoft.bond.BondMirror {
    // TODO: implement
    public com.microsoft.bond.BondSerializable clone() {return null;}

    //
    // Fields
    //

    // 1: Required int32 ProtocolVersion
    private int ProtocolVersion;

    // 2: Required org.stromberg.durandal.api.Result ExecutionResult
    private org.stromberg.durandal.api.Result ExecutionResult;

    // 3: Required bool ContinueImmediately
    private boolean ContinueImmediately;

    // 4: Optional string TextToDisplay
    private String TextToDisplay;

    // 5: Optional string UrlToOpen
    private String UrlToOpen;

    // 6: Optional string HtmlToDisplay
    private String HtmlToDisplay;

    // 7: Optional int32 SuggestedRetryDelay
    private int SuggestedRetryDelay;

    // 8: Optional string ErrorMessage
    private String ErrorMessage;

    // 9: Optional map<string, string> ResponseData
    private java.util.HashMap<String, String> ResponseData;

    // 10: Optional string AugmentedFinalQuery
    private String AugmentedFinalQuery;

    // 11: Optional nullable<org.stromberg.durandal.api.AudioData> AudioToPlay
    private org.stromberg.durandal.api.AudioData AudioToPlay;

    // 12: Optional string ResponseSSML
    private String ResponseSSML;

    // 13: Optional nullable<org.stromberg.durandal.api.RecoResult> SelectedRecoResult
    private org.stromberg.durandal.api.RecoResult SelectedRecoResult;

    // 14: Optional org.stromberg.durandal.api.UrlScope UrlScope
    private org.stromberg.durandal.api.UrlScope UrlScope;

    // 15: Optional string StreamingAudioUrl
    private String StreamingAudioUrl;

    /**
     * @return current value of ProtocolVersion property
     */
    public final int getProtocolVersion() {
        return this.ProtocolVersion;
    }

    /**
     * @param value new value of ProtocolVersion property
     */
    public final void setProtocolVersion(int value) {
        this.ProtocolVersion = value;
    }

    /**
     * @return current value of ExecutionResult property
     */
    public final org.stromberg.durandal.api.Result getExecutionResult() {
        return this.ExecutionResult;
    }

    /**
     * @param value new value of ExecutionResult property
     */
    public final void setExecutionResult(org.stromberg.durandal.api.Result value) {
        this.ExecutionResult = value;
    }

    /**
     * @return current value of ContinueImmediately property
     */
    public final boolean getContinueImmediately() {
        return this.ContinueImmediately;
    }

    /**
     * @param value new value of ContinueImmediately property
     */
    public final void setContinueImmediately(boolean value) {
        this.ContinueImmediately = value;
    }

    /**
     * @return current value of TextToDisplay property
     */
    public final String getTextToDisplay() {
        return this.TextToDisplay;
    }

    /**
     * @param value new value of TextToDisplay property
     */
    public final void setTextToDisplay(String value) {
        this.TextToDisplay = value;
    }

    /**
     * @return current value of UrlToOpen property
     */
    public final String getUrlToOpen() {
        return this.UrlToOpen;
    }

    /**
     * @param value new value of UrlToOpen property
     */
    public final void setUrlToOpen(String value) {
        this.UrlToOpen = value;
    }

    /**
     * @return current value of HtmlToDisplay property
     */
    public final String getHtmlToDisplay() {
        return this.HtmlToDisplay;
    }

    /**
     * @param value new value of HtmlToDisplay property
     */
    public final void setHtmlToDisplay(String value) {
        this.HtmlToDisplay = value;
    }

    /**
     * @return current value of SuggestedRetryDelay property
     */
    public final int getSuggestedRetryDelay() {
        return this.SuggestedRetryDelay;
    }

    /**
     * @param value new value of SuggestedRetryDelay property
     */
    public final void setSuggestedRetryDelay(int value) {
        this.SuggestedRetryDelay = value;
    }

    /**
     * @return current value of ErrorMessage property
     */
    public final String getErrorMessage() {
        return this.ErrorMessage;
    }

    /**
     * @param value new value of ErrorMessage property
     */
    public final void setErrorMessage(String value) {
        this.ErrorMessage = value;
    }

    /**
     * @return current value of ResponseData property
     */
    public final java.util.HashMap<String, String> getResponseData() {
        return this.ResponseData;
    }

    /**
     * @param value new value of ResponseData property
     */
    public final void setResponseData(java.util.HashMap<String, String> value) {
        this.ResponseData = value;
    }

    /**
     * @return current value of AugmentedFinalQuery property
     */
    public final String getAugmentedFinalQuery() {
        return this.AugmentedFinalQuery;
    }

    /**
     * @param value new value of AugmentedFinalQuery property
     */
    public final void setAugmentedFinalQuery(String value) {
        this.AugmentedFinalQuery = value;
    }

    /**
     * @return current value of AudioToPlay property
     */
    public final org.stromberg.durandal.api.AudioData getAudioToPlay() {
        return this.AudioToPlay;
    }

    /**
     * @param value new value of AudioToPlay property
     */
    public final void setAudioToPlay(org.stromberg.durandal.api.AudioData value) {
        this.AudioToPlay = value;
    }

    /**
     * @return current value of ResponseSSML property
     */
    public final String getResponseSSML() {
        return this.ResponseSSML;
    }

    /**
     * @param value new value of ResponseSSML property
     */
    public final void setResponseSSML(String value) {
        this.ResponseSSML = value;
    }

    /**
     * @return current value of SelectedRecoResult property
     */
    public final org.stromberg.durandal.api.RecoResult getSelectedRecoResult() {
        return this.SelectedRecoResult;
    }

    /**
     * @param value new value of SelectedRecoResult property
     */
    public final void setSelectedRecoResult(org.stromberg.durandal.api.RecoResult value) {
        this.SelectedRecoResult = value;
    }

    /**
     * @return current value of UrlScope property
     */
    public final org.stromberg.durandal.api.UrlScope getUrlScope() {
        return this.UrlScope;
    }

    /**
     * @param value new value of UrlScope property
     */
    public final void setUrlScope(org.stromberg.durandal.api.UrlScope value) {
        this.UrlScope = value;
    }

    /**
     * @return current value of StreamingAudioUrl property
     */
    public final String getStreamingAudioUrl() {
        return this.StreamingAudioUrl;
    }

    /**
     * @param value new value of StreamingAudioUrl property
     */
    public final void setStreamingAudioUrl(String value) {
        this.StreamingAudioUrl = value;
    }

    /**
     * Schema metadata
     */
    public static class Schema {
        public static final com.microsoft.bond.SchemaDef schemaDef;
        public static final com.microsoft.bond.Metadata metadata;
        private static final com.microsoft.bond.Metadata ProtocolVersion_metadata;
        private static final com.microsoft.bond.Metadata ExecutionResult_metadata;
        private static final com.microsoft.bond.Metadata ContinueImmediately_metadata;
        private static final com.microsoft.bond.Metadata TextToDisplay_metadata;
        private static final com.microsoft.bond.Metadata UrlToOpen_metadata;
        private static final com.microsoft.bond.Metadata HtmlToDisplay_metadata;
        private static final com.microsoft.bond.Metadata SuggestedRetryDelay_metadata;
        private static final com.microsoft.bond.Metadata ErrorMessage_metadata;
        private static final com.microsoft.bond.Metadata ResponseData_metadata;
        private static final com.microsoft.bond.Metadata AugmentedFinalQuery_metadata;
        private static final com.microsoft.bond.Metadata AudioToPlay_metadata;
        private static final com.microsoft.bond.Metadata ResponseSSML_metadata;
        private static final com.microsoft.bond.Metadata SelectedRecoResult_metadata;
        private static final com.microsoft.bond.Metadata UrlScope_metadata;
        private static final com.microsoft.bond.Metadata StreamingAudioUrl_metadata;

        static {
            metadata = new com.microsoft.bond.Metadata();
            metadata.setName("ClientResponse");
            metadata.setQualified_name("org.stromberg.durandal.api.ClientResponse");


            // ProtocolVersion
            ProtocolVersion_metadata = new com.microsoft.bond.Metadata();
            ProtocolVersion_metadata.setName("ProtocolVersion");
            ProtocolVersion_metadata.setModifier(com.microsoft.bond.Modifier.Required);
            ProtocolVersion_metadata.getDefault_value().setInt_value(6);

            // ExecutionResult
            ExecutionResult_metadata = new com.microsoft.bond.Metadata();
            ExecutionResult_metadata.setName("ExecutionResult");
            ExecutionResult_metadata.setModifier(com.microsoft.bond.Modifier.Required);
            ExecutionResult_metadata.getDefault_value().setInt_value(org.stromberg.durandal.api.Result.Failure.getValue());

            // ContinueImmediately
            ContinueImmediately_metadata = new com.microsoft.bond.Metadata();
            ContinueImmediately_metadata.setName("ContinueImmediately");
            ContinueImmediately_metadata.setModifier(com.microsoft.bond.Modifier.Required);
            ContinueImmediately_metadata.getDefault_value().setUint_value(0);

            // TextToDisplay
            TextToDisplay_metadata = new com.microsoft.bond.Metadata();
            TextToDisplay_metadata.setName("TextToDisplay");
            TextToDisplay_metadata.getDefault_value().setString_value("");

            // UrlToOpen
            UrlToOpen_metadata = new com.microsoft.bond.Metadata();
            UrlToOpen_metadata.setName("UrlToOpen");
            UrlToOpen_metadata.getDefault_value().setString_value("");

            // HtmlToDisplay
            HtmlToDisplay_metadata = new com.microsoft.bond.Metadata();
            HtmlToDisplay_metadata.setName("HtmlToDisplay");
            HtmlToDisplay_metadata.getDefault_value().setString_value("");

            // SuggestedRetryDelay
            SuggestedRetryDelay_metadata = new com.microsoft.bond.Metadata();
            SuggestedRetryDelay_metadata.setName("SuggestedRetryDelay");
            SuggestedRetryDelay_metadata.getDefault_value().setInt_value(0);

            // ErrorMessage
            ErrorMessage_metadata = new com.microsoft.bond.Metadata();
            ErrorMessage_metadata.setName("ErrorMessage");
            ErrorMessage_metadata.getDefault_value().setString_value("");

            // ResponseData
            ResponseData_metadata = new com.microsoft.bond.Metadata();
            ResponseData_metadata.setName("ResponseData");

            // AugmentedFinalQuery
            AugmentedFinalQuery_metadata = new com.microsoft.bond.Metadata();
            AugmentedFinalQuery_metadata.setName("AugmentedFinalQuery");
            AugmentedFinalQuery_metadata.getDefault_value().setString_value("");

            // AudioToPlay
            AudioToPlay_metadata = new com.microsoft.bond.Metadata();
            AudioToPlay_metadata.setName("AudioToPlay");

            // ResponseSSML
            ResponseSSML_metadata = new com.microsoft.bond.Metadata();
            ResponseSSML_metadata.setName("ResponseSSML");
            ResponseSSML_metadata.getDefault_value().setString_value("");

            // SelectedRecoResult
            SelectedRecoResult_metadata = new com.microsoft.bond.Metadata();
            SelectedRecoResult_metadata.setName("SelectedRecoResult");

            // UrlScope
            UrlScope_metadata = new com.microsoft.bond.Metadata();
            UrlScope_metadata.setName("UrlScope");
            UrlScope_metadata.getDefault_value().setInt_value(org.stromberg.durandal.api.UrlScope.Unknown.getValue());

            // StreamingAudioUrl
            StreamingAudioUrl_metadata = new com.microsoft.bond.Metadata();
            StreamingAudioUrl_metadata.setName("StreamingAudioUrl");
            StreamingAudioUrl_metadata.getDefault_value().setString_value("");

            schemaDef = new com.microsoft.bond.SchemaDef();
            schemaDef.setRoot(getTypeDef(schemaDef));
        }

        public static com.microsoft.bond.TypeDef getTypeDef(com.microsoft.bond.SchemaDef schema)
        {
            com.microsoft.bond.TypeDef type = new com.microsoft.bond.TypeDef();
            type.setId(com.microsoft.bond.BondDataType.BT_STRUCT);
            type.setStruct_def(getStructDef(schema));
            return type;
        }

        private static short getStructDef(com.microsoft.bond.SchemaDef schema)
        {
            short pos;

            for(pos = 0; pos < schema.getStructs().size(); pos++)
            {
                if (schema.getStructs().get(pos).getMetadata() == metadata)
                {
                    return pos;
                }
            }

            com.microsoft.bond.StructDef structDef = new com.microsoft.bond.StructDef();
            schema.getStructs().add(structDef);

            structDef.setMetadata(metadata);

            com.microsoft.bond.FieldDef field;

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)1);
            field.setMetadata(ProtocolVersion_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_INT32);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)2);
            field.setMetadata(ExecutionResult_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_INT32);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)3);
            field.setMetadata(ContinueImmediately_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_BOOL);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)4);
            field.setMetadata(TextToDisplay_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)5);
            field.setMetadata(UrlToOpen_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)6);
            field.setMetadata(HtmlToDisplay_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)7);
            field.setMetadata(SuggestedRetryDelay_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_INT32);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)8);
            field.setMetadata(ErrorMessage_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)9);
            field.setMetadata(ResponseData_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_MAP);
            field.getType().setKey(new com.microsoft.bond.TypeDef());
            field.getType().setElement(new com.microsoft.bond.TypeDef());
            field.getType().getKey().setId(com.microsoft.bond.BondDataType.BT_STRING);
            field.getType().getElement().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)10);
            field.setMetadata(AugmentedFinalQuery_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)11);
            field.setMetadata(AudioToPlay_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_LIST);
            field.getType().setElement(new com.microsoft.bond.TypeDef());
            field.getType().setElement(org.stromberg.durandal.api.AudioData.Schema.getTypeDef(schema));
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)12);
            field.setMetadata(ResponseSSML_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)13);
            field.setMetadata(SelectedRecoResult_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_LIST);
            field.getType().setElement(new com.microsoft.bond.TypeDef());
            field.getType().setElement(org.stromberg.durandal.api.RecoResult.Schema.getTypeDef(schema));
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)14);
            field.setMetadata(UrlScope_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_INT32);
            structDef.getFields().add(field);

            field = new com.microsoft.bond.FieldDef();
            field.setId((short)15);
            field.setMetadata(StreamingAudioUrl_metadata);
            field.getType().setId(com.microsoft.bond.BondDataType.BT_STRING);
            structDef.getFields().add(field);

            return pos;
        }
    }

    /*
    * @see com.microsoft.bond.BondMirror#getField()
    */
    public Object getField(com.microsoft.bond.FieldDef fieldDef) {
        switch (fieldDef.getId()) {
            case (short)1:
                return this.ProtocolVersion;
            case (short)2:
                return this.ExecutionResult;
            case (short)3:
                return this.ContinueImmediately;
            case (short)4:
                return this.TextToDisplay;
            case (short)5:
                return this.UrlToOpen;
            case (short)6:
                return this.HtmlToDisplay;
            case (short)7:
                return this.SuggestedRetryDelay;
            case (short)8:
                return this.ErrorMessage;
            case (short)9:
                return this.ResponseData;
            case (short)10:
                return this.AugmentedFinalQuery;
            case (short)11:
                return this.AudioToPlay;
            case (short)12:
                return this.ResponseSSML;
            case (short)13:
                return this.SelectedRecoResult;
            case (short)14:
                return this.UrlScope;
            case (short)15:
                return this.StreamingAudioUrl;
            default:
                return null;
        }
    }


    /*
    * @see com.microsoft.bond.BondMirror#setField()
    */
    public void setField(com.microsoft.bond.FieldDef fieldDef, Object value) {
        switch (fieldDef.getId()) {
            case (short)1:
                this.ProtocolVersion = (Integer)value;
                break;
            case (short)2:
                this.ExecutionResult = (org.stromberg.durandal.api.Result)value;
                break;
            case (short)3:
                this.ContinueImmediately = (Boolean)value;
                break;
            case (short)4:
                this.TextToDisplay = (String)value;
                break;
            case (short)5:
                this.UrlToOpen = (String)value;
                break;
            case (short)6:
                this.HtmlToDisplay = (String)value;
                break;
            case (short)7:
                this.SuggestedRetryDelay = (Integer)value;
                break;
            case (short)8:
                this.ErrorMessage = (String)value;
                break;
            case (short)9:
                this.ResponseData = (java.util.HashMap<String, String>)value;
                break;
            case (short)10:
                this.AugmentedFinalQuery = (String)value;
                break;
            case (short)11:
                this.AudioToPlay = (org.stromberg.durandal.api.AudioData)value;
                break;
            case (short)12:
                this.ResponseSSML = (String)value;
                break;
            case (short)13:
                this.SelectedRecoResult = (org.stromberg.durandal.api.RecoResult)value;
                break;
            case (short)14:
                this.UrlScope = (org.stromberg.durandal.api.UrlScope)value;
                break;
            case (short)15:
                this.StreamingAudioUrl = (String)value;
                break;
        }
    }


    /*
    * @see com.microsoft.bond.BondMirror#createInstance()
    */
    public com.microsoft.bond.BondMirror createInstance(com.microsoft.bond.StructDef structDef) {
        if (org.stromberg.durandal.api.AudioData.Schema.metadata == structDef.getMetadata()) {
            return new org.stromberg.durandal.api.AudioData();
        }

        if (org.stromberg.durandal.api.RecoResult.Schema.metadata == structDef.getMetadata()) {
            return new org.stromberg.durandal.api.RecoResult();
        }

        return null;
    }

    /*
     * @see com.microsoft.bond.BondMirror#getSchema()
     */
    public com.microsoft.bond.SchemaDef getSchema()
    {
        return getRuntimeSchema();
    }

    /**
     * Static method returning {@link SchemaDef} instance.
     */
    public static com.microsoft.bond.SchemaDef getRuntimeSchema()
    {
        return Schema.schemaDef;
    }

    // Constructor
    public ClientResponse() {
        reset();
    }

    /*
     * @see com.microsoft.bond.BondSerializable#reset()
     */
    public void reset() {
        reset("ClientResponse", "org.stromberg.durandal.api.ClientResponse");
    }

    protected void reset(String name, String qualifiedName) {
        
        ProtocolVersion = 6;
        ExecutionResult = org.stromberg.durandal.api.Result.Failure;
        ContinueImmediately = false;
        TextToDisplay = "";
        UrlToOpen = "";
        HtmlToDisplay = "";
        SuggestedRetryDelay = 0;
        ErrorMessage = "";
        if (ResponseData == null) {
            ResponseData = new java.util.HashMap<String, String>();
        } else {
            ResponseData.clear();
        }
        AugmentedFinalQuery = "";
        AudioToPlay = null;
        ResponseSSML = "";
        SelectedRecoResult = null;
        UrlScope = org.stromberg.durandal.api.UrlScope.Unknown;
        StreamingAudioUrl = "";
    }

    /*
     * @see com.microsoft.bond.BondSerializable#unmarshal()
     */
    public void unmarshal(java.io.InputStream input) throws java.io.IOException {
        com.microsoft.bond.internal.Marshaler.unmarshal(input, this);
    }

    /*
     * @see com.microsoft.bond.BondSerializable#unmarshal()
     */
    public void unmarshal(java.io.InputStream input, com.microsoft.bond.BondSerializable schema) throws java.io.IOException {
        com.microsoft.bond.internal.Marshaler.unmarshal(input, (com.microsoft.bond.SchemaDef)schema, this);
    }

    /*
     * @see com.microsoft.bond.BondSerializable#read()
     */
    public void read(com.microsoft.bond.ProtocolReader reader) throws java.io.IOException {
        reader.readBegin();
        readImpl(reader);
        reader.readEnd();
    }

    /*
     * Called to read a struct that is contained inside another struct.
     */
    public void readImpl(com.microsoft.bond.ProtocolReader reader) throws java.io.IOException {
        if (!reader.hasCapability(com.microsoft.bond.ProtocolCapability.TAGGED)) {
            readUntagged(reader, false);
        } else if (readTagged(reader, false)) {
            com.microsoft.bond.internal.ReadHelper.skipPartialStruct(reader);
        }
    }

    /*
     * @see com.microsoft.bond.BondSerializable#read()
     */
    public void read(com.microsoft.bond.ProtocolReader reader, com.microsoft.bond.BondSerializable schema) throws java.io.IOException {
        // read(com.microsoft.bond.internal.ProtocolHelper.createReader(reader, schema));
    }

    protected void readUntagged(com.microsoft.bond.ProtocolReader reader, boolean isBase) throws java.io.IOException {
        boolean canOmitFields = reader.hasCapability(com.microsoft.bond.ProtocolCapability.CAN_OMIT_FIELDS);

        reader.readStructBegin(isBase);
        

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.ProtocolVersion = reader.readInt32();
        }
        else
        {
            // throw new BondException("Missing required field \"ProtocolVersion\", id=1");
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.ExecutionResult = org.stromberg.durandal.api.Result.fromValue(reader.readInt32());
        }
        else
        {
            // throw new BondException("Missing required field \"ExecutionResult\", id=2");
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.ContinueImmediately = reader.readBool();
        }
        else
        {
            // throw new BondException("Missing required field \"ContinueImmediately\", id=3");
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.TextToDisplay = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.UrlToOpen = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.HtmlToDisplay = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.SuggestedRetryDelay = reader.readInt32();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.ErrorMessage = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.readFieldImpl_ResponseData(reader, com.microsoft.bond.BondDataType.BT_MAP);
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.AugmentedFinalQuery = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.readFieldImpl_AudioToPlay(reader, com.microsoft.bond.BondDataType.BT_LIST);
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.ResponseSSML = reader.readString();
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.readFieldImpl_SelectedRecoResult(reader, com.microsoft.bond.BondDataType.BT_LIST);
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.UrlScope = org.stromberg.durandal.api.UrlScope.fromValue(reader.readInt32());
        }

        if (!canOmitFields || !reader.readFieldOmitted()) {
            this.StreamingAudioUrl = reader.readString();
        }
        reader.readStructEnd();
    } // ReadUntagged()


    protected boolean readTagged(com.microsoft.bond.ProtocolReader reader, boolean isBase) throws java.io.IOException {
        boolean isPartial;
        reader.readStructBegin(isBase);

        // BitArray seenRequiredFields = new BitArray(4);

        while (true) {
            com.microsoft.bond.ProtocolReader.FieldTag fieldTag = reader.readFieldBegin();

            if (fieldTag.type == com.microsoft.bond.BondDataType.BT_STOP
             || fieldTag.type == com.microsoft.bond.BondDataType.BT_STOP_BASE) {
                isPartial = (fieldTag.type == com.microsoft.bond.BondDataType.BT_STOP_BASE);
                break;
            }

            switch (fieldTag.id) {
                case 1:
                    this.ProtocolVersion = com.microsoft.bond.internal.ReadHelper.readInt32(reader, fieldTag.type);
                    // seenRequiredFields.Set(1, true);
                    break;
                case 2:
                    this.ExecutionResult = org.stromberg.durandal.api.Result.fromValue(com.microsoft.bond.internal.ReadHelper.readInt32(reader, fieldTag.type));
                    // seenRequiredFields.Set(2, true);
                    break;
                case 3:
                    this.ContinueImmediately = com.microsoft.bond.internal.ReadHelper.readBool(reader, fieldTag.type);
                    // seenRequiredFields.Set(3, true);
                    break;
                case 4:
                    this.TextToDisplay = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 5:
                    this.UrlToOpen = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 6:
                    this.HtmlToDisplay = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 7:
                    this.SuggestedRetryDelay = com.microsoft.bond.internal.ReadHelper.readInt32(reader, fieldTag.type);
                    break;
                case 8:
                    this.ErrorMessage = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 9:
                    this.readFieldImpl_ResponseData(reader, fieldTag.type);
                    break;
                case 10:
                    this.AugmentedFinalQuery = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 11:
                    this.readFieldImpl_AudioToPlay(reader, fieldTag.type);
                    break;
                case 12:
                    this.ResponseSSML = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                case 13:
                    this.readFieldImpl_SelectedRecoResult(reader, fieldTag.type);
                    break;
                case 14:
                    this.UrlScope = org.stromberg.durandal.api.UrlScope.fromValue(com.microsoft.bond.internal.ReadHelper.readInt32(reader, fieldTag.type));
                    break;
                case 15:
                    this.StreamingAudioUrl = com.microsoft.bond.internal.ReadHelper.readString(reader, fieldTag.type);
                    break;
                default:
                    reader.skip(fieldTag.type);
                    break;
            }

            reader.readFieldEnd();
        }

        reader.readStructEnd();

        //checkRequiredFieldsAreSeen(seenRequiredFields);
        return isPartial;
    }


    private void readFieldImpl_ResponseData(com.microsoft.bond.ProtocolReader reader, com.microsoft.bond.BondDataType typeInPayload) throws java.io.IOException {
        com.microsoft.bond.internal.ReadHelper.validateType(typeInPayload, com.microsoft.bond.BondDataType.BT_MAP);
    
        com.microsoft.bond.ProtocolReader.MapTag tag1 = reader.readMapContainerBegin();
    
        for (int i2 = 0; i2 < tag1.size; i2++) {
            String key3 = "";
            String val4 = "";
    
            // Read key
                key3 = com.microsoft.bond.internal.ReadHelper.readString(reader, tag1.keyType);
    
            // Read value
                val4 = com.microsoft.bond.internal.ReadHelper.readString(reader, tag1.valueType);
            //
            this.ResponseData.put(key3, val4);
        }
    
        reader.readContainerEnd();
    } // readFieldImpl_ResponseData


    private void readFieldImpl_AudioToPlay(com.microsoft.bond.ProtocolReader reader, com.microsoft.bond.BondDataType typeInPayload) throws java.io.IOException {
        com.microsoft.bond.internal.ReadHelper.validateType(typeInPayload, com.microsoft.bond.BondDataType.BT_LIST);
    
        com.microsoft.bond.ProtocolReader.ListTag tag1 = reader.readContainerBegin();
        com.microsoft.bond.internal.ReadHelper.validateType(tag1.type, com.microsoft.bond.BondDataType.BT_STRUCT);
    
        if (tag1.size == 1) {
            if (this.AudioToPlay == null) { this.AudioToPlay = new org.stromberg.durandal.api.AudioData(); }    this.AudioToPlay.readImpl(reader);
        } else if (tag1.size != 0) {
            // throw new com.microsoft.bond.ProtocolException("Unexpected size for Nullable. Expecting size<=1, got size=" + tag1.size);
        }
    
    
        reader.readContainerEnd();
    } // readFieldImpl_AudioToPlay


    private void readFieldImpl_SelectedRecoResult(com.microsoft.bond.ProtocolReader reader, com.microsoft.bond.BondDataType typeInPayload) throws java.io.IOException {
        com.microsoft.bond.internal.ReadHelper.validateType(typeInPayload, com.microsoft.bond.BondDataType.BT_LIST);
    
        com.microsoft.bond.ProtocolReader.ListTag tag1 = reader.readContainerBegin();
        com.microsoft.bond.internal.ReadHelper.validateType(tag1.type, com.microsoft.bond.BondDataType.BT_STRUCT);
    
        if (tag1.size == 1) {
            if (this.SelectedRecoResult == null) { this.SelectedRecoResult = new org.stromberg.durandal.api.RecoResult(); }    this.SelectedRecoResult.readImpl(reader);
        } else if (tag1.size != 0) {
            // throw new com.microsoft.bond.ProtocolException("Unexpected size for Nullable. Expecting size<=1, got size=" + tag1.size);
        }
    
    
        reader.readContainerEnd();
    } // readFieldImpl_SelectedRecoResult


    /*
     * @see com.microsoft.bond.BondSerializable#marshal()
     */
    public void marshal(com.microsoft.bond.ProtocolWriter writer) throws java.io.IOException {
        com.microsoft.bond.internal.Marshaler.marshal(this, writer);
    }

    /*
     * @see com.microsoft.bond.BondSerializable#write()
     */
    public void write(com.microsoft.bond.ProtocolWriter writer) throws java.io.IOException {
        writer.writeBegin();
        com.microsoft.bond.ProtocolWriter firstPassWriter;
        if ((firstPassWriter = writer.getFirstPassWriter()) != null)
        {
            writeImpl(firstPassWriter, false);
            writeImpl(writer, false);
        }
        else
        {
          writeImpl(writer, false);
        }
        writer.writeEnd();
    }

    public void writeImpl(com.microsoft.bond.ProtocolWriter writer, boolean isBase) throws java.io.IOException {
        boolean canOmitFields = writer.hasCapability(com.microsoft.bond.ProtocolCapability.CAN_OMIT_FIELDS);
        writer.writeStructBegin(Schema.metadata, isBase);
        

        writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_INT32, 1, Schema.ProtocolVersion_metadata);
        writer.writeInt32(ProtocolVersion);
        writer.writeFieldEnd();

        writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_INT32, 2, Schema.ExecutionResult_metadata);
        writer.writeInt32(ExecutionResult.getValue());
        writer.writeFieldEnd();

        writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_BOOL, 3, Schema.ContinueImmediately_metadata);
        writer.writeBool(ContinueImmediately);
        writer.writeFieldEnd();

        if (!canOmitFields || (TextToDisplay != Schema.TextToDisplay_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 4, Schema.TextToDisplay_metadata);
            writer.writeString(TextToDisplay);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 4, Schema.TextToDisplay_metadata);
        }

        if (!canOmitFields || (UrlToOpen != Schema.UrlToOpen_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 5, Schema.UrlToOpen_metadata);
            writer.writeString(UrlToOpen);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 5, Schema.UrlToOpen_metadata);
        }

        if (!canOmitFields || (HtmlToDisplay != Schema.HtmlToDisplay_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 6, Schema.HtmlToDisplay_metadata);
            writer.writeString(HtmlToDisplay);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 6, Schema.HtmlToDisplay_metadata);
        }

        if (!canOmitFields || (SuggestedRetryDelay != Schema.SuggestedRetryDelay_metadata.getDefault_value().getInt_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_INT32, 7, Schema.SuggestedRetryDelay_metadata);
            writer.writeInt32(SuggestedRetryDelay);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_INT32, 7, Schema.SuggestedRetryDelay_metadata);
        }

        if (!canOmitFields || (ErrorMessage != Schema.ErrorMessage_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 8, Schema.ErrorMessage_metadata);
            writer.writeString(ErrorMessage);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 8, Schema.ErrorMessage_metadata);
        }

        int size6 = (ResponseData.size());
        if (!canOmitFields || (size6 != 0)) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_MAP, 9, Schema.ResponseData_metadata);
            writer.writeContainerBegin(ResponseData.size(), com.microsoft.bond.BondDataType.BT_STRING, com.microsoft.bond.BondDataType.BT_STRING);
            for (java.util.Map.Entry<String, String> e7 : ResponseData.entrySet()) {
                // Key
                writer.writeString(e7.getKey());
                // Value
                writer.writeString(e7.getValue());
            }
            writer.writeContainerEnd();
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_MAP, 9, Schema.ResponseData_metadata);
        }

        if (!canOmitFields || (AugmentedFinalQuery != Schema.AugmentedFinalQuery_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 10, Schema.AugmentedFinalQuery_metadata);
            writer.writeString(AugmentedFinalQuery);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 10, Schema.AugmentedFinalQuery_metadata);
        }

        int size9 = (AudioToPlay != null) ? 1 : 0;
        if (!canOmitFields || (size9 != 0)) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_LIST, 11, Schema.AudioToPlay_metadata);
            writer.writeContainerBegin(size9, com.microsoft.bond.BondDataType.BT_STRUCT);
            if (size9 != 0) {
                AudioToPlay.writeImpl(writer, false);
            }
            writer.writeContainerEnd();
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_LIST, 11, Schema.AudioToPlay_metadata);
        }

        if (!canOmitFields || (ResponseSSML != Schema.ResponseSSML_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 12, Schema.ResponseSSML_metadata);
            writer.writeString(ResponseSSML);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 12, Schema.ResponseSSML_metadata);
        }

        int size11 = (SelectedRecoResult != null) ? 1 : 0;
        if (!canOmitFields || (size11 != 0)) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_LIST, 13, Schema.SelectedRecoResult_metadata);
            writer.writeContainerBegin(size11, com.microsoft.bond.BondDataType.BT_STRUCT);
            if (size11 != 0) {
                SelectedRecoResult.writeImpl(writer, false);
            }
            writer.writeContainerEnd();
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_LIST, 13, Schema.SelectedRecoResult_metadata);
        }

        if (!canOmitFields || (UrlScope.getValue() != Schema.UrlScope_metadata.getDefault_value().getInt_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_INT32, 14, Schema.UrlScope_metadata);
            writer.writeInt32(UrlScope.getValue());
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_INT32, 14, Schema.UrlScope_metadata);
        }

        if (!canOmitFields || (StreamingAudioUrl != Schema.StreamingAudioUrl_metadata.getDefault_value().getString_value())) {
            writer.writeFieldBegin(com.microsoft.bond.BondDataType.BT_STRING, 15, Schema.StreamingAudioUrl_metadata);
            writer.writeString(StreamingAudioUrl);
            writer.writeFieldEnd();
        } else {
            writer.writeFieldOmitted(com.microsoft.bond.BondDataType.BT_STRING, 15, Schema.StreamingAudioUrl_metadata);
        }

        writer.writeStructEnd(isBase);
    } // writeImpl


    public boolean memberwiseCompare(Object obj) {
        if (obj == null) {
            return false;
        }

        ClientResponse that = (ClientResponse)obj;

        return memberwiseCompareQuick(that) && memberwiseCompareDeep(that);
    }

    protected boolean memberwiseCompareQuick(ClientResponse that) {
        boolean equals = true;
        
        equals = equals && (this.ProtocolVersion == that.ProtocolVersion);
        equals = equals && (this.ExecutionResult == that.ExecutionResult);
        equals = equals && (this.ContinueImmediately == that.ContinueImmediately);
        equals = equals && ((this.TextToDisplay == null) == (that.TextToDisplay == null));
        equals = equals && (this.TextToDisplay == null ? true : (this.TextToDisplay.length() == that.TextToDisplay.length()));
        equals = equals && ((this.UrlToOpen == null) == (that.UrlToOpen == null));
        equals = equals && (this.UrlToOpen == null ? true : (this.UrlToOpen.length() == that.UrlToOpen.length()));
        equals = equals && ((this.HtmlToDisplay == null) == (that.HtmlToDisplay == null));
        equals = equals && (this.HtmlToDisplay == null ? true : (this.HtmlToDisplay.length() == that.HtmlToDisplay.length()));
        equals = equals && (this.SuggestedRetryDelay == that.SuggestedRetryDelay);
        equals = equals && ((this.ErrorMessage == null) == (that.ErrorMessage == null));
        equals = equals && (this.ErrorMessage == null ? true : (this.ErrorMessage.length() == that.ErrorMessage.length()));
        equals = equals && ((this.ResponseData == null) == (that.ResponseData == null));
        equals = equals && ((this.ResponseData == null) ? true : (this.ResponseData.size() == that.ResponseData.size()));
        equals = equals && ((this.AugmentedFinalQuery == null) == (that.AugmentedFinalQuery == null));
        equals = equals && (this.AugmentedFinalQuery == null ? true : (this.AugmentedFinalQuery.length() == that.AugmentedFinalQuery.length()));
        equals = equals && ((this.AudioToPlay == null) == (that.AudioToPlay == null));
        equals = equals && ((this.ResponseSSML == null) == (that.ResponseSSML == null));
        equals = equals && (this.ResponseSSML == null ? true : (this.ResponseSSML.length() == that.ResponseSSML.length()));
        equals = equals && ((this.SelectedRecoResult == null) == (that.SelectedRecoResult == null));
        equals = equals && (this.UrlScope == that.UrlScope);
        equals = equals && ((this.StreamingAudioUrl == null) == (that.StreamingAudioUrl == null));
        equals = equals && (this.StreamingAudioUrl == null ? true : (this.StreamingAudioUrl.length() == that.StreamingAudioUrl.length()));
        return equals;
    } // memberwiseCompareQuick

    protected boolean memberwiseCompareDeep(ClientResponse that) {
        boolean equals = true;
        
        equals = equals && (this.TextToDisplay == null ? true : this.TextToDisplay.equals(that.TextToDisplay));
        equals = equals && (this.UrlToOpen == null ? true : this.UrlToOpen.equals(that.UrlToOpen));
        equals = equals && (this.HtmlToDisplay == null ? true : this.HtmlToDisplay.equals(that.HtmlToDisplay));
        equals = equals && (this.ErrorMessage == null ? true : this.ErrorMessage.equals(that.ErrorMessage));
        if (equals && this.ResponseData != null && this.ResponseData.size() != 0)
        {
            for (java.util.Map.Entry<String, String> e3 : this.ResponseData.entrySet()) {
                String val1 = e3.getValue();
                String val2 = that.ResponseData.get(e3.getKey());
                equals = equals && that.ResponseData.containsKey(e3.getKey());
                if (equals) {
                    equals = equals && ((val1 == null) == (val2 == null));
                    equals = equals && (val1 == null ? true : (val1.length() == val2.length()));
                    equals = equals && (val1 == null ? true : val1.equals(val2));
                }
                if (!equals) {
                    break;
                }
            }
        }
        equals = equals && (this.AugmentedFinalQuery == null ? true : this.AugmentedFinalQuery.equals(that.AugmentedFinalQuery));
        if (equals && !(this.AudioToPlay == null)) {
            equals = equals && ((this.AudioToPlay == null) == (that.AudioToPlay == null));
            equals = equals && (this.AudioToPlay == null ? true : this.AudioToPlay.memberwiseCompare(that.AudioToPlay));
        }
        equals = equals && (this.ResponseSSML == null ? true : this.ResponseSSML.equals(that.ResponseSSML));
        if (equals && !(this.SelectedRecoResult == null)) {
            equals = equals && ((this.SelectedRecoResult == null) == (that.SelectedRecoResult == null));
            equals = equals && (this.SelectedRecoResult == null ? true : this.SelectedRecoResult.memberwiseCompare(that.SelectedRecoResult));
        }
        equals = equals && (this.StreamingAudioUrl == null ? true : this.StreamingAudioUrl.equals(that.StreamingAudioUrl));
        return equals;
    } // memberwiseCompareDeep

}; // class ClientResponse
