



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.not
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : org\stromberg\durandal\api\InputMethod.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package org.stromberg.durandal.api;


/**
* InputMethod
*/
public enum InputMethod {
    Unknown(0),
    Typed(1),
    Spoken(2),
    Programmatic(3),
    __INVALID_ENUM_VALUE(4);

    private final int value;

    InputMethod(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public static InputMethod fromValue(int value) {
        switch (value) {
            case 0:
                return Unknown;
            case 1:
                return Typed;
            case 2:
                return Spoken;
            case 3:
                return Programmatic;
        }
        return __INVALID_ENUM_VALUE;
    }
}; // enum InputMethod

