



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.not
//     Template : Microsoft.Bond.Rules.dll#Java.tt
//     File     : org\stromberg\durandal\api\SlotValueFormat.java
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
package org.stromberg.durandal.api;


/**
* SlotValueFormat
*/
public enum SlotValueFormat {
    TypedText(0),
    SpokenText(1),
    CrossDomainTag(2),
    DialogActionParameter(3),
    __INVALID_ENUM_VALUE(4);

    private final int value;

    SlotValueFormat(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public static SlotValueFormat fromValue(int value) {
        switch (value) {
            case 0:
                return TypedText;
            case 1:
                return SpokenText;
            case 2:
                return CrossDomainTag;
            case 3:
                return DialogActionParameter;
        }
        return __INVALID_ENUM_VALUE;
    }
}; // enum SlotValueFormat

